web:
  image: asia-southeast1-docker.pkg.dev/project-669c83f6-d64c-4648-b15/robot-shop/web
  tag: latest
cart:
  image: asia-southeast1-docker.pkg.dev/project-669c83f6-d64c-4648-b15/robot-shop/cart
  tag: 6500ee19247e0cfb8fd14728c41fc0e5623682e2
catalogue:
  image: asia-southeast1-docker.pkg.dev/project-669c83f6-d64c-4648-b15/robot-shop/catalogue
  tag: fb02f73fef77ca46dc5050fe30ade394a9688d90
dispatch:
  image: asia-southeast1-docker.pkg.dev/project-669c83f6-d64c-4648-b15/robot-shop/dispatch
  tag: latest
payment:
  image: asia-southeast1-docker.pkg.dev/project-669c83f6-d64c-4648-b15/robot-shop/payment
  tag: fb02f73fef77ca46dc5050fe30ade394a9688d90
ratings:
  image: asia-southeast1-docker.pkg.dev/project-669c83f6-d64c-4648-b15/robot-shop/ratings
  tag: latest
shipping:
  image: asia-southeast1-docker.pkg.dev/project-669c83f6-d64c-4648-b15/robot-shop/shipping
  tag: fb02f73fef77ca46dc5050fe30ade394a9688d90
user:
  image: asia-southeast1-docker.pkg.dev/project-669c83f6-d64c-4648-b15/robot-shop/user
  tag: latest
aiops:
  image: asia-southeast1-docker.pkg.dev/project-669c83f6-d64c-4648-b15/robot-shop/aiops-inference
  tag: 5fdf1275dfd5e11491440510d1c85dd27dd33466
ai-ops:
  tag: b59459052b1553c2c5a0c8f5c3cef15c4cd0f8fe
