web:
  image: asia-southeast1-docker.pkg.dev/project-669c83f6-d64c-4648-b15/robot-shop/web
  tag: 5e2061be37d33fff89517ac2ac4c1df2ff45c4dc
cart:
  image: asia-southeast1-docker.pkg.dev/project-669c83f6-d64c-4648-b15/robot-shop/cart
  tag: "27984a1cb5721423754aff2c36fb8084cd03d355"
catalogue:
  image: asia-southeast1-docker.pkg.dev/project-669c83f6-d64c-4648-b15/robot-shop/catalogue
  tag: "fa75ce2961abd83af935a28ceab84e812402eb6f"
dispatch:
  image: asia-southeast1-docker.pkg.dev/project-669c83f6-d64c-4648-b15/robot-shop/dispatch
  tag: "latest"
payment:
  image: asia-southeast1-docker.pkg.dev/project-669c83f6-d64c-4648-b15/robot-shop/payment
  tag: "latest"
ratings:
  image: asia-southeast1-docker.pkg.dev/project-669c83f6-d64c-4648-b15/robot-shop/ratings
  tag: "0cb49d3764b0d4917e772c94db2b61cbb0eb2934"
shipping:
  image: asia-southeast1-docker.pkg.dev/project-669c83f6-d64c-4648-b15/robot-shop/shipping
  tag: "latest"
user:
  image: asia-southeast1-docker.pkg.dev/project-669c83f6-d64c-4648-b15/robot-shop/user
  tag: "latest"
