# Registry and repository for Docker images
# Default is docker/robotshop/image:latest
image:
  repo: robotshop
  version: latest
  pullPolicy: IfNotPresent

# EUM configuration
# Provide your key and set the endpoint
eum:
  key: null
  url: https://eum-eu-west-1.instana.io
  #url: https://eum-us-west-2.instana.io

# Pod Security Policy
psp:
  enabled: false

# For the mini ones minikube, minishift set to true
nodeport: false

# "special" Openshift. Set to true when deploying to any openshift flavour
openshift: false

ocCreateRoute: false

######################################
# Affinities for individual workloads
# set in the following way:
# <workload>:
#   affinity: {}
#   nodeSelector: {}
#   tolerations: []
######################################

cart: {}

catalogue: {}

dispatch: {}

mongodb: {}

mysql: {}

payment:
  # Alternative payment gateway URL
  # Default is https://www.paypal.com
  gateway: null
  #gateway: https://www.worldpay.com

rabbitmq: {}

ratings: {}

redis:
  # Storage class to use with redis statefulset.
  storageClassName: standard

shipping: {}

user: {}

web: {}

aiops:
  image: asia-southeast1-docker.pkg.dev/project-669c83f6-d64c-4648-b15/robot-shop/aiops
  tag: latest

# KEDA và HPA thường không cần image riêng, nhưng nếu bạn cần bật/tắt chúng
# thì nên thêm biến này để điều khiển trong template:
keda:
  enabled: true

hpa:
  enabled: true